### ISSUE TITLE
migration not working

### ISSUE THREAD

**Issue by eliasbui** [trueai-org/module-shop#19]
![image](https://github.com/trueai-org/module-shop/assets/88380128/d3caffa4-c3c7-4abe-9b6c-ca519308b496)

help me fix @trueai-org

**Comment by trueai-org** [comment]
Data already exists in the database. All migration commands are invalid. You are advised to delete the database and test again

see Doc: https://learn.microsoft.com/zh-cn/ef/core/

**Comment by eliasbui** [comment]
I fix done thank pro
